export { default as Header } from './common/Header'
export { default as Loader } from './common/Loader'
export { default as Menu } from './common/Menu'
export { default as Button } from './common/Button'
export { default as NonExistRoutes } from './page/NonExistRoutes'
export { default as PrivacyTermsAndConditions } from './common/PrivacyToc'